config/routes.rb
Timesheets::Application.routes.draw do  

  resources :users, :sessions

  resources :timesheets do
    collection do
      get 'datepicker'
    end
  end

  namespace "admin" do
	resources :timesheets
  end

  get "home/index"

  root :to => "home#index"

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
    belongs_to :user
    has_many :timesheet_days, :order => "date_worked"

    accepts_nested_attributes_for :timesheet_days, :allow_destroy => true,
        :reject_if => proc { |attributes| attributes['date_worked'].blank? }

    #after_update :add_days

    #def add_days
    #    self.timesheet_days.
    #end
end

app/controllers/admin/timesheets_controller.rb
class Admin::TimesheetsController < ApplicationController
    #layout "administrator"

    before_filter :verify_admin_access

    # GET /timesheets
    # GET /timesheets.xml
    def index
        @users = User.find(:all, :order => "username")
        #@timesheets = Timesheet.all
        #@timesheets = Timesheet.find(:all)

	if params["status"] && !params["status"].empty? && params["timesheet_user_id"] && !params["timesheet_user_id"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["status=? and user_id=?" , params["status"], params["timesheet_user_id"]])
	elsif params["status"] && !params["status"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["status=?" , params["status"]])
	elsif params["timesheet_user_id"] && !params["timesheet_user_id"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["user_id=?" , params["timesheet_user_id"]])
	else
            @timesheets = Timesheet.find(:all)# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)"
	end

        #session['status'] = params["status"] if params["status"] && !params["status"].empty?
        #session['timesheet_user_id'] = params["timesheet_user_id"] if params["timesheet_user_id"] && !params["timesheet_user_id"].empty?

        respond_to do |format|
            format.html # index.html.erb
            #format.xml  { render :xml => @timesheets }
        end
    end

    # GET /timesheets/1
    # GET /timesheets/1.xml
    def show

        #puts("==============SHOW==============")
        #puts("params[:tid]=#{params[:id]}")
        @timesheet = Timesheet.find(params[:id])
        #puts("params[:id]=#{params[:id]}")

        respond_to do |format|
            #format.html # show.html.erb
            #format.xml  { render :xml => @timesheet }
            format.js{}
        end
    end

    # GET /timesheets/new
    # GET /timesheets/new.xml
    def new
        @timesheet = Timesheet.new

        respond_to do |format|
            format.html # new.html.erb
            #format.xml  { render :xml => @timesheet }
        end
    end

    # GET /timesheets/1/edit
    def edit
        @timesheet = Timesheet.find(params[:id])
    end

    # POST /timesheets
    # POST /timesheets.xml
    def create
        @timesheet = Timesheet.new(params[:timesheet])

        respond_to do |format|
            #if @timesheet.save
                    #flash[:notice] = 'Timesheet was successfully created.'
            #	format.html { redirect_to(@timesheet) }
                    #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            #else
            #	format.html { render :action => "new" }
                    #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            #end

            if @timesheet.save
                #format.html { redirect_to(@timesheet,	:notice => 'Timesheet was successfully created.') }
                format.html { redirect_to :controller => "admin/timesheets", :action => "show", :id => @timesheet.id }
                #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
                format.html { render :action => "new" }
                #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /timesheets/1
    # PUT /timesheets/1.xml
    def update
        @timesheet = Timesheet.find(params[:id])

        respond_to do |format|
            if @timesheet.update_attributes(params[:timesheet])
            #flash[:notice] = 'Timesheet was successfully updated.'
            #format.html { redirect_to(@timesheet) }
            #format.xml  { head :ok }
                #session['status'] if session["status"] && session["status"].empty?
                #session['timesheet_user_id'] if session["timesheet_user_id"] && session["timesheet_user_id"].empty?
                format.html { redirect_to :controller => "admin/timesheets", :action => "index" }
              #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
            #format.html { render :action => "edit" }
            #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }

              format.html { render :action => "new" }
              #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /timesheets/1
    # DELETE /timesheets/1.xml
    def destroy
        @timesheet = Timesheet.find(params[:id])
        @timesheet.destroy

        respond_to do |format|
            format.html { redirect_to(admin_timesheets_url) }
            #format.xml  { head :ok }
        end
    end

  private
    def verify_admin_access
        if !@current_user.administrator
            redirect_to(new_session_path)
        end
    end

end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController

    before_filter :ensure_login
    before_filter :verify_admin_access, :only => [:show, :edit, :update, :destroy]

    # GET /timesheets
    # GET /timesheets.xml
    def index
        #@timesheets = Timesheet.all
        #@timesheets = Timesheet.find(:all)
        @timesheets = @current_user.timesheets
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @timesheets }
        end
    end

    # GET /timesheets/1
    # GET /timesheets/1.xml
    def show
#        @timesheet = Timesheet.find(params[:id])
        respond_to do |format|
            #format.html # show.html.erb
            #format.xml  { render :xml => @timesheet }
            format.js{}
        end
    end

    def datepicker
        respond_to do |format|
            format.js{}
        end
    end

    # GET /timesheets/new
    # GET /timesheets/new.xml
    def new
        @timesheet = @current_user.timesheets.build
        #@timesheet.status = 0
        #day_date = Time.now
        #day_date = "2010/2/8".to_date
        day_date = params[:start].to_date unless params[:start].nil?
        day_date = Time.now if params[:start].nil?
        day_span = params[:span].to_i unless params[:span].nil?
        day_span = 14 if params[:span].nil?
        if day_date.wday <= 1
             day_span.times { |i|
                if day_date.wday > 0 && day_date.wday < 6
                    day = @timesheet.timesheet_days.build
                    day.index = i
                    day.date_worked = day_date.to_s.split(" ")[0]
                end
                day_date = day_date.tomorrow
            }

            respond_to do |format|
                #format.html # new.html.erb
                #format.xml  { render :xml => @timesheet }
                format.js{}
            end
        end
    end

    # GET /timesheets/1/edit
    def edit
#        @timesheet = Timesheet.find(params[:id])
        respond_to do |format|
            #format.html # show.html.erb
            format.js{}
        end
    end

    # POST /timesheets
    # POST /timesheets.xml
    def create
        #@timesheet = Timesheet.new(params[:timesheet])
        @timesheet = @current_user.timesheets.build(params[:timesheet])
        @timesheet.status = 0
        #@day = @timesheet.timesheet_days.build
        #@day.date_worked = Time.now
        #@day.begin_time_in_minutes = 60
        #@day.end_time_in_minutes = 120
        #@day.total_time_in_minutes = 60
        #@day.save

        respond_to do |format|
            if @timesheet.save
                format.html { redirect_to :controller => "timesheets", :action => "index", :id => @timesheet.id }
                #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
                format.html { render :action => "new" }
                #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /timesheets/1
    # PUT /timesheets/1.xml
    def update
#        @timesheet = Timesheet.find(params[:id])
        @timesheet.status = 0
        respond_to do |format|
            if @timesheet.update_attributes(params[:timesheet])
              format.html { redirect_to :controller => "timesheets", :action => "index", :id => @timesheet.id }
              #format.xml  { render :xml => @timesheet, :status => :updated, :location => @timesheet }
            else
              format.html { render :action => "new" }
              #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /timesheets/1
    # DELETE /timesheets/1.xml
    def destroy
#        @timesheet = Timesheet.find(params[:id])
        @timesheet.destroy

        respond_to do |format|
            format.html { redirect_to(timesheets_url) }
            format.xml  { head :ok }
        end
    end

  private
    def verify_admin_access
        @timesheet = Timesheet.find(params[:id])
        if !@current_user.administrator && @timesheet.user_id != @current_user.id
            redirect_to(timesheets_url)
        end
    end

end

app/helpers/admin/timesheets_helper.rb
module Admin::TimesheetsHelper

end

app/helpers/timesheets_helper.rb
module TimesheetsHelper

    def write_weekday(the_date)
        case the_date.wday
        when 0
            return "Sunday"
        when 1
            return "Monday"
        when 2
            return "Tuesday"
        when 3
            return "Wednesday"
        when 4
            return "Thursday"
        when 5
            return "Friday"
        when 6
            return "Saturday"
        end
    end

    def status_display(status)
        case status
        when 0
            return "PENDING"
        when 1
            return "REJECTED"
        when 2
            return "APPROVED"
        end
    end

    def convert_to_us_date_string(date_str)
        date_parts = date_str.to_s.split( /-/ )
        "#{date_parts[1]}/#{date_parts[2]}/#{date_parts[0]}"
    end

    def convert_to_time_string(mins)
        timestr = []
        meridian = " am"
        time_in_mins = mins
        if mins >= 60
            hrs = time_in_mins / 60
            hrs = hrs.floor

            if hrs > 12
                meridian = " pm"
                hrs -= 12
            elsif hrs == 12
                meridian = " pm"
            end

            if hrs <= 9
                timestr << "0#{hrs}"
            else
                timestr << "#{hrs}"
            end
            time_in_mins %= 60
        else
            timestr.push("12")
        end
        timestr << ":"
        if time_in_mins <= 9
            timestr << "0#{time_in_mins}"
        else
            timestr << "#{time_in_mins}"
        end
        timestr << meridian
        timestr.join("")
    end

    def convert_to_hours_string(mins)
		sprintf('%.2f', (mins.to_f/60.00))
    end
end

app/views/timesheets/_datepicker.html.erb
<h1 class="dialog_header">Select Timesheet Start Date</h1>
<style type="text/css">
/* located in demo.css and creates a little calendar icon
 * instead of a text link for "Choose date"
 */
a.dp-choose-date {
	float: left;
	width: 16px;
	height: 16px;
	padding: 0;
	margin: 5px 3px 0;
	display: block;
	text-indent: -2000px;
	overflow: hidden;
	background: url(../../images/calendar.png) no-repeat;
}
a.dp-choose-date.dp-disabled {
	background-position: 0 -20px;
	cursor: default;
}
/* makes the input field shorter once the date picker code
 * has run (to allow space for the calendar icon
 */
input.dp-applied {
	width: 140px;
	float: left;
}
</style>
<div style="width:400px;">

    <div style="float:left;font-size:10pt;padding-right:10px;">Select Starting Date:</div><input type="text" id="start" readonly="readonly"/>

</div>
<div style="clear:both"></div>

<script type="text/javascript">
jQuery(function()
{
    Date.format = 'mm/dd/yyyy'
    jQuery('#start').datePicker({
        startDate: "01/01/2000",
        selectWeek:true,
        closeOnSelect:false
    });
});
function convertDate(str1)
{
    var date_parts = str1.split('/');
    return date_parts[2] + "/" + date_parts[0] + "/" + date_parts[1];
}
//alert(convertDate("12/5/2010"))
</script>

<br/>
<hr/>

<%=render :partial=>"common/remote_button", :locals=>{:label=>"Continue",
          :remote_function=>remote_function(:url=>new_timesheet_path, :method=>:get, :with=>"'start=' + convertDate(jQuery('#start').val())")}%>
<%=render :partial=>"common/close_button"%>

app/views/timesheets/_edit.html.erb
<h1 class="dialog_header">Edit Timesheet</h1>
Current Status: <%=status_display(@timesheet.status)%>
<%if @timesheet.status != 2%>
<%=render :partial=>"form"%>
<%end%>

<hr/>

<%#= button_to 'Cancel', timesheet_path(@timesheet), :method=>:get, :class=>"button inline-left" %>
<%#=render :partial=>"common/button", :locals=>{:title=>"Cancel", :link=>timesheet_path(@timesheet), :custom_class=>"inline-left"}%>
<%#= button_to 'Back to Timesheets', timesheets_path, :method=>:get, :class=>"button inline-left" %>
<%#=render :partial=>"common/button", :locals=>{:title=>"Back to Timesheets", :link=>timesheets_path}%>
<%=render :partial=>"common/close_button"%>

app/views/timesheets/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<% form_for @timesheet, :html=>{:onsubmit=>"return buildForm();"} do |f| %>
<%#= f.error_messages %>

<div class="timecard">

    <div class="tr">
        <div class="td" style="border-left:1px dotted #000000;width:185px;"><%=t("timesheets.fields.date")%></div>
        <div class="td" style="width:300px;"><%=t("timesheets.fields.location")%></div>
        <div class="td"><%=t("timesheets.fields.start_time")%></div>
        <div class="td"><%=t("timesheets.fields.end_time")%></div>
        <div class="td"><%=t("timesheets.fields.total_hours")%></div>
    </div>
    <div style="clear:left;"></div>
  <% i = 0 %>
  <% f.fields_for :timesheet_days do |day| %>
    <%= day.text_field :index, :style=>"display:none;" %>
    <div class="tr">
        <div class="td" style="border-left:1px dotted #000000;width:185px;">
            <%= day.text_field :date_worked, :class=>"date", :style=>"width:78px;display:none;" %>
            <%=convert_to_us_date_string(@timesheet.timesheet_days[i].date_worked)%>
            (<%=write_weekday(@timesheet.timesheet_days[i].date_worked)%>)
        </div>
        <div class="td" style="width:300px;"><%= day.text_field :location, :style=>"width:290px" %></div>
        <div class="td">
            <%= day.text_field :begin_time_in_minutes, :style=>"display:none;" %>
            <input type="text" class="time" style="width:78px;"/>
        </div>
        <div class="td">
            <%= day.text_field :end_time_in_minutes, :style=>"display:none;" %>
            <input type="text" class="time" style="width:78px;"/>
        </div>
        <div class="td">
            <%= day.text_field :total_time_in_minutes, :style=>"display:none" %>
            <input type="text" class="total" style="width:78px;"/>
        </div>
    </div>
    <div style="clear:left;"></div>
    <% i += 1 %>
  <% end %>

</div>

<%= f.submit 'Save', :class=>"button inline-left ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" %>
<div style="clear:left"/>
<% end %>

<script type="text/javascript">
jQuery(".date").attr('readonly', true);
jQuery(function(){
    // Initialize 'time' fields
    jQuery("input[id$=begin_time_in_minutes], input[id$=end_time_in_minutes]").each(function(){
        var fld = jQuery(this).next();
        if(fld.attr("class")=="time"){//} || fld.attr("class")=="hasTimeEntry"){
            if(jQuery(this).val().length>0) fld.val(convertToTimeString(parseInt(jQuery(this).val())));
        }
    });
    // Initialize 'hours' field
    jQuery("input[id$=total_time_in_minutes]").each(function(){
        var fld = jQuery(this).next();
        if(fld.attr("class")=="total"){
            if(jQuery(this).val().length>0) fld.val(convertToHoursString(parseInt(jQuery(this).val())));
        }
    });
    // Initialize controls
    //jQuery(".time").timeEntry();
    jQuery('.time').timepickr({
        convention:12,
        trigger:"click",
        updateLive:false
    });
    jQuery('.total').numeric({allow:"."});
})
function buildForm(){
    jQuery("input[id$=begin_time_in_minutes], input[id$=end_time_in_minutes]").each(function(){
        var fld = jQuery(this).next();//.children("input:first-child");
        //if(fld.attr("class")=="time hasTimeEntry"){
        if(fld.hasClass("time")){
            if(fld.val().length>0){
                jQuery(this).val(convertFromTimeString(fld.val()));
            }
        }
    });
    jQuery("input[id$=total_time_in_minutes]").each(function(){
        var fld = jQuery(this).next();
        if(fld.attr("class")=="total"){
            if(fld.val().length>0){
                jQuery(this).val(convertFromHoursString(fld.val()));
            }
        }
    });
    return true;
}
</script>

app/views/timesheets/_new.html.erb
<h1 class="dialog_header">New Timesheet</h1>

<%=render :partial=>"form"%>

<hr/>

<%#= button_to 'Cancel', timesheets_path, :method=>:get, :class=>"button inline-left" %>
<%#=render :partial=>"common/button", :locals=>{:title=>"Cancel", :link=>timesheets_path}%>
<%=render :partial=>"common/close_button"%>

app/views/timesheets/_show.html.erb
<h1 class="dialog_header">View Timesheet</h1>


Current Status: <%=status_display(@timesheet.status)%>
<%=render :partial=>"timesheets/timesheet"%>

<hr/>

<%if @timesheet.status != 2%>
<%#= button_to 'Edit', edit_timesheet_path(@timesheet), :method=>:get, :class=>"button inline-left" %>
<%#=render :partial=>"common/button", :locals=>{:title=>"Edit", :link=>edit_timesheet_path(@timesheet), :custom_class=>"inline-left"}%>
<%=render :partial=>"common/remote_button", :locals=>{:label=>"Edit",
          :remote_function=>remote_function(:url=>edit_timesheet_path(@timesheet), :method=>:get, :with=>"r=#{rand(10000)}")}%>

<%end%>
<%#= button_to 'Back to Timesheets', timesheets_path, :method=>:get, :class=>"button inline-left" %>
<%=render :partial=>"common/close_button"%>

app/views/timesheets/_timesheet.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>


<div class="timecard">

    <div class="tr">
        <div class="td" style="width:185px;border-left:1px dotted #000000;">Date</div>
        <div class="td" style="width:300px;">Location</div>
        <div class="td">Start Time</div>
        <div class="td">End Time</div>
        <div class="td">Total Hours</div>
    </div>
    <div style="clear:left;"></div>

    <% @timesheet.timesheet_days.each do |day| %>
    <div class="tr">
        <div class="td" style="border-left:1px dotted #000000;width:185px;">
            <%=convert_to_us_date_string(day.date_worked)%>
            <strong>(<%=write_weekday(day.date_worked)%>)</strong>
        </div>
        <div class="td" style="width:300px;"><%=h day.location%></div>
        <div class="td">
        <% unless day.begin_time_in_minutes.blank? %>
            <%=convert_to_time_string(day.begin_time_in_minutes)%>
        <% end %>
        </div>
        <div class="td">
        <% unless day.end_time_in_minutes.blank? %>
            <%=convert_to_time_string(day.end_time_in_minutes)%>
        <% end %>
        </div>
        <div class="td">
        <% unless day.total_time_in_minutes.blank? %>
            <%=convert_to_hours_string(day.total_time_in_minutes)%>
        <% end %>
        </div>
    </div>
    <div style="clear:left;"></div>
    <% end %>

</div>

app/views/timesheets/_timesheet_status.html.erb
<%
case status
when 0
%>
<span style="color:#000000;font-weight:bolder;"><%=status_display(status)%></span>
<%
when 1
%>
<span style="color:#C00000;font-weight:bolder;"><%=status_display(status)%></span>
<%
when 2
%>
<span style="color:#07AF07;font-weight:bolder;"><%=status_display(status)%></span>
<%
end
%>

app/views/timesheets/index.html.erb
<h1 class="page_header">My Timesheets</h1>

<%=render :partial=>"common/remote_button", :locals=>{:label=>"New Timesheet",
          :remote_function=>remote_function(:url=>datepicker_timesheets_path, :method=>:get)}%>
<div style="clear:both"></div>
<div id="timesheets">

<%
@timesheets.each do |timesheet|
    days = timesheet.timesheet_days
    if days.length > 0
%>
    <div class="tr">
        <!-- Timecard Display -->

        <div class="td">
            <span class="title">
            <%=convert_to_us_date_string(days[0].date_worked)%>
            &nbsp;-&nbsp;
            <%=convert_to_us_date_string(days[days.length-1].date_worked)%>
            </span>
            <span class="status">
                <%=render :partial=>"timesheet_status", :locals=>{:status=>timesheet.status}%>
            </span>
        </div>
        <div class="td">
            <%#= button_to "Edit", edit_timesheet_path(timesheet), :method=>:get, :class=>"button inline-left" %>
            <%=render :partial=>"common/remote_button", :locals=>{:label=>"View",
                      :remote_function=>remote_function(:url=>timesheet_path(timesheet), :method=>:get, :with=>"r=#{rand(10000)}")}%>

            <%if timesheet.status != 2%>
            <%=render :partial=>"common/button", :locals=>{:title=>"Delete", :link=>timesheet_path(timesheet), :custom_class=>"inline-left",
                        :method=>:delete, :confirm=>"Are you sure you want to delete this timesheet?"}%>
            <%end%>
        </div>

        <!-- Timecard Display -->
    </div>
    <div style="clear:left;"></div>
    <% end %>
<% end %>
</div>