config/routes.rb
Timesheets::Application.routes.draw do  

  resources :users, :sessions

  resources :timesheets do
    collection do
      get 'datepicker'
    end
  end

  namespace "admin" do
	resources :timesheets
  end

  get "home/index"

  root :to => "home#index"

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
    belongs_to :user
    has_many :timesheet_days, :order => "date_worked"

    accepts_nested_attributes_for :timesheet_days, :allow_destroy => true,
        :reject_if => proc { |attributes| attributes['date_worked'].blank? }

    #after_update :add_days

    #def add_days
    #    self.timesheet_days.
    #end
end

app/controllers/admin/timesheets_controller.rb
class Admin::TimesheetsController < ApplicationController
    #layout "administrator"

    before_filter :verify_admin_access

    # GET /timesheets
    # GET /timesheets.xml
    def index
        @users = User.find(:all, :order => "username")
        #@timesheets = Timesheet.all
        #@timesheets = Timesheet.find(:all)

	if params["status"] && !params["status"].empty? && params["timesheet_user_id"] && !params["timesheet_user_id"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["status=? and user_id=?" , params["status"], params["timesheet_user_id"]])
	elsif params["status"] && !params["status"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["status=?" , params["status"]])
	elsif params["timesheet_user_id"] && !params["timesheet_user_id"].empty?
            @timesheets = Timesheet.find(:all,# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)",
				:conditions => ["user_id=?" , params["timesheet_user_id"]])
	else
            @timesheets = Timesheet.find(:all)# :order => "(case when priority='High' then 0 when priority='Medium' then 1 when priority='Low' then 3 else priority end)"
	end

        #session['status'] = params["status"] if params["status"] && !params["status"].empty?
        #session['timesheet_user_id'] = params["timesheet_user_id"] if params["timesheet_user_id"] && !params["timesheet_user_id"].empty?

        respond_to do |format|
            format.html # index.html.erb
            #format.xml  { render :xml => @timesheets }
        end
    end

    # GET /timesheets/1
    # GET /timesheets/1.xml
    def show

        #puts("==============SHOW==============")
        #puts("params[:tid]=#{params[:id]}")
        @timesheet = Timesheet.find(params[:id])
        #puts("params[:id]=#{params[:id]}")

        respond_to do |format|
            #format.html # show.html.erb
            #format.xml  { render :xml => @timesheet }
            format.js{}
        end
    end

    # GET /timesheets/new
    # GET /timesheets/new.xml
    def new
        @timesheet = Timesheet.new

        respond_to do |format|
            format.html # new.html.erb
            #format.xml  { render :xml => @timesheet }
        end
    end

    # GET /timesheets/1/edit
    def edit
        @timesheet = Timesheet.find(params[:id])
    end

    # POST /timesheets
    # POST /timesheets.xml
    def create
        @timesheet = Timesheet.new(params[:timesheet])

        respond_to do |format|
            #if @timesheet.save
                    #flash[:notice] = 'Timesheet was successfully created.'
            #	format.html { redirect_to(@timesheet) }
                    #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            #else
            #	format.html { render :action => "new" }
                    #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            #end

            if @timesheet.save
                #format.html { redirect_to(@timesheet,	:notice => 'Timesheet was successfully created.') }
                format.html { redirect_to :controller => "admin/timesheets", :action => "show", :id => @timesheet.id }
                #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
                format.html { render :action => "new" }
                #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /timesheets/1
    # PUT /timesheets/1.xml
    def update
        @timesheet = Timesheet.find(params[:id])

        respond_to do |format|
            if @timesheet.update_attributes(params[:timesheet])
            #flash[:notice] = 'Timesheet was successfully updated.'
            #format.html { redirect_to(@timesheet) }
            #format.xml  { head :ok }
                #session['status'] if session["status"] && session["status"].empty?
                #session['timesheet_user_id'] if session["timesheet_user_id"] && session["timesheet_user_id"].empty?
                format.html { redirect_to :controller => "admin/timesheets", :action => "index" }
              #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
            #format.html { render :action => "edit" }
            #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }

              format.html { render :action => "new" }
              #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /timesheets/1
    # DELETE /timesheets/1.xml
    def destroy
        @timesheet = Timesheet.find(params[:id])
        @timesheet.destroy

        respond_to do |format|
            format.html { redirect_to(admin_timesheets_url) }
            #format.xml  { head :ok }
        end
    end

  private
    def verify_admin_access
        if !@current_user.administrator
            redirect_to(new_session_path)
        end
    end

end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController

    before_filter :ensure_login
    before_filter :verify_admin_access, :only => [:show, :edit, :update, :destroy]

    # GET /timesheets
    # GET /timesheets.xml
    def index
        #@timesheets = Timesheet.all
        #@timesheets = Timesheet.find(:all)
        @timesheets = @current_user.timesheets
        respond_to do |format|
            format.html # index.html.erb
            format.xml  { render :xml => @timesheets }
        end
    end

    # GET /timesheets/1
    # GET /timesheets/1.xml
    def show
#        @timesheet = Timesheet.find(params[:id])
        respond_to do |format|
            #format.html # show.html.erb
            #format.xml  { render :xml => @timesheet }
            format.js{}
        end
    end

    def datepicker
        respond_to do |format|
            format.js{}
        end
    end

    # GET /timesheets/new
    # GET /timesheets/new.xml
    def new
        @timesheet = @current_user.timesheets.build
        #@timesheet.status = 0
        #day_date = Time.now
        #day_date = "2010/2/8".to_date
        day_date = params[:start].to_date unless params[:start].nil?
        day_date = Time.now if params[:start].nil?
        day_span = params[:span].to_i unless params[:span].nil?
        day_span = 14 if params[:span].nil?
        if day_date.wday <= 1
             day_span.times { |i|
                if day_date.wday > 0 && day_date.wday < 6
                    day = @timesheet.timesheet_days.build
                    day.index = i
                    day.date_worked = day_date.to_s.split(" ")[0]
                end
                day_date = day_date.tomorrow
            }

            respond_to do |format|
                #format.html # new.html.erb
                #format.xml  { render :xml => @timesheet }
                format.js{}
            end
        end
    end

    # GET /timesheets/1/edit
    def edit
#        @timesheet = Timesheet.find(params[:id])
        respond_to do |format|
            #format.html # show.html.erb
            format.js{}
        end
    end

    # POST /timesheets
    # POST /timesheets.xml
    def create
        #@timesheet = Timesheet.new(params[:timesheet])
        @timesheet = @current_user.timesheets.build(params[:timesheet])
        @timesheet.status = 0
        #@day = @timesheet.timesheet_days.build
        #@day.date_worked = Time.now
        #@day.begin_time_in_minutes = 60
        #@day.end_time_in_minutes = 120
        #@day.total_time_in_minutes = 60
        #@day.save

        respond_to do |format|
            if @timesheet.save
                format.html { redirect_to :controller => "timesheets", :action => "index", :id => @timesheet.id }
                #format.xml  { render :xml => @timesheet, :status => :created, :location => @timesheet }
            else
                format.html { render :action => "new" }
                #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # PUT /timesheets/1
    # PUT /timesheets/1.xml
    def update
#        @timesheet = Timesheet.find(params[:id])
        @timesheet.status = 0
        respond_to do |format|
            if @timesheet.update_attributes(params[:timesheet])
              format.html { redirect_to :controller => "timesheets", :action => "index", :id => @timesheet.id }
              #format.xml  { render :xml => @timesheet, :status => :updated, :location => @timesheet }
            else
              format.html { render :action => "new" }
              #format.xml  { render :xml => @timesheet.errors, :status => :unprocessable_entity }
            end
        end
    end

    # DELETE /timesheets/1
    # DELETE /timesheets/1.xml
    def destroy
#        @timesheet = Timesheet.find(params[:id])
        @timesheet.destroy

        respond_to do |format|
            format.html { redirect_to(timesheets_url) }
            format.xml  { head :ok }
        end
    end

  private
    def verify_admin_access
        @timesheet = Timesheet.find(params[:id])
        if !@current_user.administrator && @timesheet.user_id != @current_user.id
            redirect_to(timesheets_url)
        end
    end

end

app/helpers/admin/timesheets_helper.rb
module Admin::TimesheetsHelper

end

app/helpers/timesheets_helper.rb
module TimesheetsHelper

    def write_weekday(the_date)
        case the_date.wday
        when 0
            return "Sunday"
        when 1
            return "Monday"
        when 2
            return "Tuesday"
        when 3
            return "Wednesday"
        when 4
            return "Thursday"
        when 5
            return "Friday"
        when 6
            return "Saturday"
        end
    end

    def status_display(status)
        case status
        when 0
            return "PENDING"
        when 1
            return "REJECTED"
        when 2
            return "APPROVED"
        end
    end

    def convert_to_us_date_string(date_str)
        date_parts = date_str.to_s.split( /-/ )
        "#{date_parts[1]}/#{date_parts[2]}/#{date_parts[0]}"
    end

    def convert_to_time_string(mins)
        timestr = []
        meridian = " am"
        time_in_mins = mins
        if mins >= 60
            hrs = time_in_mins / 60
            hrs = hrs.floor

            if hrs > 12
                meridian = " pm"
                hrs -= 12
            elsif hrs == 12
                meridian = " pm"
            end

            if hrs <= 9
                timestr << "0#{hrs}"
            else
                timestr << "#{hrs}"
            end
            time_in_mins %= 60
        else
            timestr.push("12")
        end
        timestr << ":"
        if time_in_mins <= 9
            timestr << "0#{time_in_mins}"
        else
            timestr << "#{time_in_mins}"
        end
        timestr << meridian
        timestr.join("")
    end

    def convert_to_hours_string(mins)
		sprintf('%.2f', (mins.to_f/60.00))
    end
end

app/views/admin/timesheets/_show.html.erb
<h1 class="dialog_header">Change Timesheet Status</h1>

<div style="width:840px">
Current Status: <%=status_display(@timesheet.status)%>
<div style="float:right;width:300px;">
    <% form_for [:admin, @timesheet] do |f| %>
    <div style="float:left;">
    <%= f.submit 'Change Status', :class=>"button inline-left ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" %>
    </div>
    <div style="float:left;padding-top:5px;">
     to <%= select( "timesheet", "status", { "Pending" => "0", "Rejected" => "1", "Approved" => "2"}) %>
    </div>
    <% end %>
</div>
</div>

<div style="clear:both;"></div>

<%=render :partial=>"timesheets/timesheet"%>

<div style="float:left;">
<%=render :partial=>"common/close_button"%>
</div>

app/views/admin/timesheets/index.html.erb
<h1 class="page_header">Timesheet Administration</h1>

<div id="searchbar" style="height:30px;margin:10px;border:1px solid #000000;padding:4px;">

<div class="heading_text" style="float:left;margin-right:216px;margin-left:10px;">View </div>

<select id="status">
        <option value="">All</option>
        <option value="0">Pending</option>
        <option value="1">Rejected</option>
        <option value="2">Approved</option>
</select>

<div class="heading_text" style="float:left;margin-right:216px;"> Timeheets for </div>

<%= collection_select("timesheet", "user_id", @users, :id, :username, options ={:prompt => "All Users"}, :class =>"user") %>

</div>

<div id="tablebar" style="margin:10px;padding:4px;">

<div id="admin_timesheets">
    <div class="tr">
        <div class="td">User</div>
        <div class="td">Start</div>
        <div class="td">End</div>
        <div class="td">Status</div>
        <div class="td"></div>
    </div>
    <div style="clear:left;"></div>

<%
@timesheets.each do |timesheet|
    days = timesheet.timesheet_days
    if days.length > 0
%>
    <div class="tr">
        <div class="td">
            <%=timesheet.user.first_name%>
            <%=timesheet.user.last_name%>
        </div>
        <div class="td">
            <%=convert_to_us_date_string(days[0].date_worked)%>
        </div>
        <div class="td">
            <%=convert_to_us_date_string(days[days.length-1].date_worked)%>
        </div>
        <div class="td">
            <%=render :partial=>"/timesheets/timesheet_status", :locals=>{:status=>timesheet.status}%>
        </div>
        <div class="td">
            <%=render :partial=>"common/remote_button", :locals=>{:label=>"Change Status",
                      :remote_function=>remote_function(:url=>admin_timesheet_path(timesheet), :method=>:get, :with=>"r=#{rand(10000)}")}%>

        <%if timesheet.status != 2%>
            <%#= button_to "Delete", timesheet_path(timesheet), :method=>:delete, :class=>"button inline-left",
                            :confirm=>"Are you sure you want to delete this timesheet?" %>
            <%=render :partial=>"common/button", :locals=>{:title=>"Delete", :link=>timesheet_path(timesheet), :custom_class=>"inline-left",
                        :method=>:delete, :confirm=>"Are you sure you want to delete this timesheet?"}%>
        <%end%>
        </div>
    </div>
    <div style="clear:left;"></div>
    <% end %>
<% end %>
</div>

</div>

<script type="text/javascript">
$(function(){
    $("#status").val(getParameterByName("status"));
    $('#status').sexyselect({
        title: $("#status option:selected").text(),
        allowDelete: false,
        selectionMode: 'single',
        expanded: false,
        onItemSelected: submitSearch
    });

    $("#timesheet_user_id").val(getParameterByName("timesheet_user_id"));
    $('#timesheet_user_id').sexyselect({
        title: $("#timesheet_user_id option:selected").text(),
        allowDelete: false,
        selectionMode: 'single',
        expanded: false,
        onItemSelected: submitSearch
    });

    //$("#status").val(getParameterByName("status"));
    //$("#status").change(submitSearch);
    //$("#timesheet_user_id").val(getParameterByName("timesheet_user_id"));
    //$("#timesheet_user_id").change(submitSearch);
});
function getParameterByName( name )
{
    name = name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
    var regexS = "[\\?&]"+name+"=([^&#]*)";
    var regex = new RegExp( regexS );
    var results = regex.exec( window.location.href );
    if( results == null )
        return "";
    else
        return results[1];
}
function submitSearch()
{
    if($("#status").val().length > 0 && $("#timesheet_user_id").val().length > 0)
        document.location.search = "?timesheet_user_id=" + $("#timesheet_user_id").val() + "&status=" + $("#status").val();
    else if($("#status").val().length > 0)
        document.location.search = "?status=" + $("#status").val();
    else if($("#timesheet_user_id").val().length > 0)
        document.location.search = "?timesheet_user_id=" + $("#timesheet_user_id").val();
    else
        document.location.search = "";
}
</script>