config/routes.rb
Timesheets::Application.routes.draw do  

  resources :users, :sessions

  resources :timesheets do
    collection do
      get 'datepicker'
    end
  end

  namespace "admin" do
	resources :timesheets
  end

  get "home/index"

  root :to => "home#index"

end

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheets - Administrator</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timesheets</title>

    <!--[if gte IE 7]>
    <script src="/javascripts/DOMAssistantComplete-2.8.js" type="text/javascript"></script>
    <script src="/javascripts/ie-css3.js" type="text/javascript"></script>
    <![endif]-->

    <%#= stylesheet_link_tag :all %>
    <!--"jquery/theme/ui.all.css",-->
    <%= stylesheet_link_tag "jquery/css/base2.css",
                            "jquery/css/jquery-ui.css",
                            "jquery/css/redmond/jquery-ui-1.7.2.custom.css",
                            #"jquery/timeentry/jquery.timeentry.css",
                            "/timepickr/ui.timepickr.css",
                            "jquery/datePicker.css",
                            "/sexyselect/css/shThemeDefault.css",
                            "/fancybox/jquery.fancybox-1.3.4.css",
                            "common.css",
                            "timesheets.css"%>

    <%#= javascript_include_tag :defaults %>
    <%= javascript_include_tag "jquery/jquery-1.4.4.min.js",
                               "application.js",
                               "jquery/jquery-ui-1.8.6.custom.min.js",
                               "jquery/jquery.alphanumeric.pack.js",
                               #"jquery/timeentry/jquery.timeentry.js",
                               "/timepickr/jquery.utils.js",
                               "/timepickr/jquery.strings.js",
                               "/timepickr/jquery.anchorHandler.js",
                               "/timepickr/ui.timepickr.js",
                               "jquery/jquery.datePicker.js",
                               "/sexyselect/js/ui.sexyselect.0.4.js",
                               "jquery/date.js",
                               "/fancybox/jquery.fancybox-1.3.4.pack.js",
                               "rails.js",
                               "timesheets.js",
                               "jquery/jquery.datePicker.js"%>

    <%= csrf_meta_tag %>

    <%#= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>

</head>
<body>

    <a id="modal_dialog_link" style="display:none;" href="#modal_dialog">test</a>
    <div style="display: none;">
        <div id="modal_dialog"></div>
    </div>

    <div class="toolbar">
        <%#= button_to "Home", root_url, :class=>"button" %>
        <%=render :partial=>"common/button", :locals=>{:title=>"Home", :link=>home_index_path}%>
        <% if @current_user %>
            <%#= button_to "Edit Account", edit_user_path(@current_user), :method => :get, :class=>"button" %>
            <%=render :partial=>"common/button", :locals=>{:title=>"My Profile", :link=>edit_user_path(@current_user)}%>
            <%#= button_to "Logout", @application_session, :method => :delete, :class=>"button" %>
            <%=render :partial=>"common/button", :locals=>{:title=>"View My Timesheets", :link=>timesheets_path}%>
            <% if @current_user.administrator %>
            <%=render :partial=>"common/button", :locals=>{:title=>"Administration", :link=>admin_timesheets_path}%>
            <% end %>
            <%=render :partial=>"common/button", :locals=>{:title=>"Logout", :link=>@application_session,
                            :method=>:delete, :confirm=>"Are you sure you want to logout?"}%>
            <div style="float:right;margin-top:8px;margin-right:20px;font-size: 12pt;">Currently logged in as: <%=@current_user.username%></div>
        <% else %>
            <%#= button_to "Login", new_session_path, :method=>:get, :class=>"button" %>
            <%=render :partial=>"common/button", :locals=>{:title=>"Login", :link=>new_session_path}%>
            <%#= button_to "Register", new_user_path, :method=>:get, :class=>"button" %>
            <%=render :partial=>"common/button", :locals=>{:title=>"Register", :link=>new_user_path}%>
        <% end %>
        <div id="alert" title="Alert Message" style="display:none;"><%=h "#{flash[:notice]}" if flash[:notice] %></div>
        <div style="clear:both;"></div>
    </div>

    <script type="text/javascript">
        jQuery(function(){
            var alert_msg = jQuery("#alert").text();
            if(alert_msg.length > 0){
                //alert(alert_msg);
                //jQuery("#alert").dialog({ disabled: true });
                $("#alert").dialog({ buttons: { "Ok": function() { $(this).dialog("close"); } } });
            }
        });
    </script>

    <hr/>

    <%= yield %>

</body>
<script type="text/javascript">
jQuery(function(){
    jQuery('#modal_dialog_link').fancybox({
        autoScale: true,
        overlayShow: true,
        hideOnContentClick: false,
        onStart: function() {
            //startWait(false);
        },
        onComplete: function() {
            //stopWait();
        }
    });
});
function openModelDialog(){
    jQuery('#modal_dialog_link').fancybox().trigger('click');
}
</script>
</html>